# Generated by Django 5.2 on 2025-04-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='turno',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='turnos.horarioturno'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('cancha', 'fecha', 'horario')},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_inicio',
        ),
    ]
