# Generated by Django 5.2 on 2025-05-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_horarioturno_alter_turno_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioturno',
            options={'ordering': ['hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'horario']},
        ),
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canchas'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20),
        ),
    ]
